In [1]:
import numpy as np

## numpy array

In [2]:
benimListem= [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros 

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

## linspace

In [14]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [15]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [16]:
#linspace(x,y,z) z yerine yazdığımız değer ne ise aralarında eşit aralıklar olacak şekilde z değerlerini yazar.

## eye

In [17]:
#bir matrix olusturur.

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [20]:
np.random.randn(4)

array([0.24605077, 0.64162668, 2.34675017, 0.1963332 ])

In [22]:
np.random.randn(4,4)

array([[ 1.2861023 ,  0.89284689,  0.2315631 ,  1.26261311],
       [-1.64079585, -1.18780459,  1.65930371,  0.96388529],
       [ 1.23869048,  0.84129618,  0.20537509,  0.92351676],
       [-2.4266933 ,  0.95020129, -0.08532404,  0.04561003]])

In [23]:
np.random.randint(1,10)

8

In [24]:
np.random.randint(1,10,3)

array([1, 6, 4])

In [30]:
benimNumpyDizim= np.arange(30)

In [31]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
benimRandomDizim = np.random.randint(0,50,5)

In [33]:
benimRandomDizim

array([29, 12,  5, 46, 46])

## numpy dizi methodları

In [34]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [35]:
benimNumpyDizim.max()

29

In [36]:
benimRandomDizim.max()

46

In [37]:
benimRandomDizim.min()

5

In [38]:
benimRandomDizim.argmax()

3

In [39]:
benimRandomDizim.argmin()

2

In [40]:
benimNumpyDizim.shape

(30,)

In [41]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [43]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
reshapeDizim.shape

(5, 6)