In [1]:
import numpy as np

In [2]:
benimDizim= np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [5]:
benimDizim[3:5]

array([3, 4])

In [6]:
benimDizim[3:8]=-5

In [7]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi= np.arange(0,24)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicingDizisi = baskaDizi[4:9]

In [11]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
type(slicingDizisi)

numpy.ndarray

In [18]:
slicingDizisi[:]

array([4, 5, 6, 7, 8])

In [19]:
slicingDizisi[:]=700

In [20]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [21]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
ornekDizi= np.arange(0,24)

In [23]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekDiziKopyasi= ornekDizi.copy()

In [25]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
ornekDiziKopyaSlicing= ornekDiziKopyasi[3:6]

In [28]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [30]:
ornekDiziKopyaSlicing[:]=800

In [31]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [32]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [33]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [34]:
benimListem=[[10,20,30],[20,30,40],[30,40,50]]

In [35]:
benimMatrixDizim= np.array(benimListem)

In [36]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [37]:
benimMatrixDizim[0]

array([10, 20, 30])

In [38]:
benimMatrixDizim[1][2]

40

In [40]:
benimMatrixDizim[1,2]

40

In [43]:
benimMatrixDizim[1:,2]

array([40, 50])

## Operasyonlar

In [44]:
yeniBirDizi= np.random.randint(1,100,20)

In [45]:
yeniBirDizi

array([84, 14, 34, 47,  2, 38, 81, 36,  6, 21, 20, 37, 60, 80, 73, 80,  5,
       76, 15, 75])

In [47]:
sonucDizisi= yeniBirDizi>24

In [48]:
sonucDizisi

array([ True, False,  True,  True, False,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [49]:
yeniBirDizi

array([84, 14, 34, 47,  2, 38, 81, 36,  6, 21, 20, 37, 60, 80, 73, 80,  5,
       76, 15, 75])

In [50]:
yeniBirDizi[sonucDizisi]

array([84, 34, 47, 38, 81, 36, 37, 60, 80, 73, 80, 76, 75])

In [51]:
yeniBirDizi[yeniBirDizi>24]

array([84, 34, 47, 38, 81, 36, 37, 60, 80, 73, 80, 76, 75])

In [52]:
sonDizi = np.arange(0,24)

In [53]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [55]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [57]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [58]:
np.max(sonDizi)

23

In [59]:
np.min(sonDizi)

0